[package]
name = "rustwin"
version = "0.0.1"
authors = ["JonathanS <mail@strfry.org>"]

[dependencies]

#camera_capture = "0.5.0"
#glium = "0.18.1"

libc = "0.2.43"
rustc-serialize = "0.3.24" 
portaudio = "0.7.0"
